language: python
addons:
  firefox: latest
cache: pip
python:
  - 2.7
  - 3.6

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 10 # give xvfb some time to start
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.18.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
install:
  - pip install -U tox
  - pip install -U pip
script:
  - tox -r
env:
  - TOXENV=django18
  - TOXENV=django110
  - TOXENV=django111
notifications:
  email: false
sudo: false
